alias init="cmake -Htest -Bbuild"
alias initdbg="cmake -DCMAKE_BUILD_TYPE=Debug -Htest -Bbuild"
alias build="cmake --build build"
alias clean="rm -rf build"
alias verbose_build="cmake --build build -- VERBOSE=1"
alias run="build/test_bluenoise"
alias debug="lldb -o run build/test_msquares"
